POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Juan José Sierra",
    "number": "123-456-78"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Just The Name"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "Just The Number"
}